import 'dart:math';

class WordHint {
  final String word;
  final String hint;

  WordHint(this.word, this.hint);
}

// Initial list of words with hints
final List<WordHint> hangmanWordList = [
  WordHint("FLUTTER", "A Google UI toolkit for building natively compiled apps"),
  WordHint("DART", "Programming language used by Flutter"),
  WordHint("PROGRAM", "A set of instructions for a computer"),
  WordHint("COMPUTER", "A device that executes programs"),
  WordHint("MOBILE", "Device category including smartphones and tablets"),
  WordHint("WIDGET", "Basic building block of Flutter UI"),
  WordHint("NETWORK", "System of interconnected computers"),
  WordHint("VARIABLE", "Storage location paired with a symbolic name"),
  WordHint("PACKAGE", "A set of software that can be reused"),
  WordHint("SKELETON", "The supporting framework of a structure"),
  WordHint("PROVIDER", "A way to manage state in Flutter apps"),
  WordHint("ALGORITHM", "A step-by-step procedure for solving a problem"),
  WordHint("BINARY", "Number system with base 2, using 0 and 1"),
  WordHint("BYTE", "A unit of digital information usually 8 bits"),
  WordHint("CACHE", "A small, fast memory storage closer to CPU"),
  WordHint("COMPILER", "A program that translates source code into machine code"),
  WordHint("DATABASE", "Organized collection of data"),
  WordHint("DEBUG", "Process of finding and fixing errors"),
  WordHint("CLASS", "Blueprint or template for creating objects"),
  WordHint("OBJECT", "Instance of a class"),
  WordHint("FUNCTION", "Reusable block of code that performs a task"),
  WordHint("FRAMEWORK", "A platform for developing software applications"),
  WordHint("GITHUB", "Platform for hosting and collaborating on code"),
  WordHint("HASH", "Function that maps data to fixed-size values"),
  WordHint("HTML", "Markup language for web pages"),
  WordHint("HTTP", "Protocol used for transferring web pages"),
  WordHint("ICON", "A graphical representation of a program or function"),
  WordHint("IDE", "Integrated Development Environment for coding"),
  WordHint("INLINE", "Code inserted directly in place for optimization"),
  WordHint("INTEGER", "Whole number data type"),
  WordHint("INTERFACE", "Defines a contract or set of methods a class must implement"),
  WordHint("JSON", "Lightweight data-interchange format"),
  WordHint("KEYBOARD", "Input device with keys"),
  WordHint("LAMBDA", "Anonymous function expression"),
  WordHint("LOOP", "Construct to repeat code multiple times"),
  WordHint("MATRIX", "Two-dimensional array of numbers"),
  WordHint("METHOD", "Function inside a class"),
  WordHint("MODULE", "Reusable piece of software"),
  WordHint("NETWORKING", "Connecting computers to share data"),
  WordHint("OBJECTIVE", "Goal or purpose in programming"),
  WordHint("OPERATING", "Type of system software managing computer resources"),
  WordHint("PACKAGE", "Collection of related software components"),
  WordHint("PARAMETER", "Variable passed to functions or methods"),
  WordHint("PARSER", "Program that analyzes data format"),
  WordHint("POLYMORPHISM", "Ability of objects to take many forms"),
  WordHint("QUEUE", "Data structure following FIFO (First In, First Out)"),
  WordHint("RECURSION", "Function calling itself"),
  WordHint("REGEX", "Pattern matching syntax"),
  WordHint("RENDER", "Process of drawing on screen"),
  WordHint("REPOSITORY", "Storage location for code"),
  WordHint("SCOPE", "Visibility context of variables"),
  WordHint("STACK", "Data structure following LIFO (Last In, First Out)"),
  WordHint("STRING", "Sequence of characters"),
  WordHint("SYNTAX", "Set of rules for programming language"),
  WordHint("THREAD", "Sequence of executable instructions"),
  WordHint("TOKEN", "Basic element in language parsing"),
  WordHint("VARIABLE", "Storage location with a name"),
  WordHint("VIRTUAL", "Simulated rather than physical"),
  WordHint("WEBHOOK", "Callback triggered by events"),
  WordHint("XML", "Markup language for storing data"),
  WordHint("YAML", "Human-friendly data serialization format"),
  WordHint("ZIP", "Compressed file format"),
  WordHint("API", "Interface for communication between software"),
  WordHint("ASYNC", "Code that executes asynchronously"),
  WordHint("BROWSER", "Software to view web pages"),
  WordHint("BYTECODE", "Intermediate code executed by virtual machine"),
  WordHint("BOOLEAN", "Data type with true/false values"),
  WordHint("CONSTRUCTOR", "Special function to initialize objects"),
  WordHint("DESTRUCTOR", "Function to clean up objects"),
  WordHint("ENCAPSULATION", "Wrapping data and methods in a class"),
  WordHint("EVENT", "Action or occurrence that can be detected"),
  WordHint("EXTENSION", "Add functionality without subclassing"),
  WordHint("FLOAT", "Number with decimals"),
  WordHint("GARBAGE", "Unused memory reclaimed automatically"),
  WordHint("HEAP", "Memory area for dynamic allocation"),
  WordHint("IMPORT", "Bring external code into current file"),
  WordHint("INDEX", "Position indicator in arrays"),
  WordHint("INLINE", "Embedding code directly"),
  WordHint("ITERATOR", "Object that enables looping over elements"),
  WordHint("LINT", "Tool to find programming errors"),
  WordHint("MOBILE", "Handheld computing device"),
  WordHint("NAMESPACE", "Container for identifiers"),
  WordHint("NULL", "Represents no value"),
  WordHint("OBJECTIVE", "Relating to objects or goals"),
  WordHint("OVERLOAD", "Multiple definitions of function/operator"),
  WordHint("PACKAGE", "Bundled code and resources"),
  WordHint("POLICY", "Set of rules or guidelines"),
  WordHint("PRIMITIVE", "Basic data type"),
  WordHint("REFERENCE", "Pointer to another value"),
  WordHint("RETURN", "Exit a function and optionally return data"),
  WordHint("SEMANTICS", "Meaning of code"),
  WordHint("SERVER", "Computer that provides services"),
  WordHint("SESSION", "User interaction period"),
  WordHint("STACKTRACE", "List of function calls at an error"),
  WordHint("STATIC", "Fixed and unchanging"),
  WordHint("STRINGIFY", "Convert data to string"),
  WordHint("STRUCTURE", "Organization of data"),
  WordHint("SUBCLASS", "Derived class from a parent class"),
  WordHint("SWITCH", "Control flow statement"),
  WordHint("SYNTAX", "Rules defining code structure"),
  WordHint("THREAD", "Execution path in program"),
  WordHint("TOKEN", "Unit of code or data"),
  WordHint("TRANSPILE", "Convert code to another language"),
  WordHint("TRY", "Block to test exceptions"),
  WordHint("UNION", "Type that can hold different data types"),
  WordHint("VARIABLE", "Declared storage for data"),
  WordHint("VERSION", "Specific state or release of software"),
  WordHint("VIRTUAL", "Function overridden at runtime"),
  WordHint("WEB", "Global information system of connected documents"),
  WordHint("YIELD", "Pause and resume a generator function"),
  WordHint("ZONE", "Execution context in asynchronous programming"),
  WordHint("ABSTRACTION", "Hiding complex reality while exposing only necessary parts"),
  WordHint("AGILE", "A software development methodology"),
  WordHint("APIKEY", "Key used to authenticate API requests"),
  WordHint("APPLICATION", "A software program for end users"),
  WordHint("ARTIFICIAL", "Related to intelligence demonstrated by machines"),
  WordHint("ASYNC", "Programming with asynchronous operations"),
  WordHint("BACKEND", "Server-side part of an application"),
  WordHint("BINARYTREE", "Tree data structure with at most two children"),
  WordHint("BOOLEANLOGIC", "Logical operations on true/false values"),
  WordHint("BRANCH", "A copy of code diverging from mainline"),
  WordHint("BUCKET", "Storage container for data, often in databases"),
  WordHint("BYTEARRAY", "An array of bytes"),
  WordHint("CACHING", "Storing data temporarily to speed up access"),
  WordHint("CALLBACK", "Function passed as an argument to be executed later"),
  WordHint("CERTIFICATE", "Digital document used for encryption"),
  WordHint("CLOUD", "Remote servers hosted on the internet"),
  WordHint("CODEBASE", "The entire collection of source code"),
  WordHint("CONCURRENT", "Executing multiple processes simultaneously"),
  WordHint("CONDITION", "Expression controlling flow in code"),
  WordHint("CONFIGURATION", "Settings for software or hardware"),
  WordHint("CONSOLE", "Text-based interface for interacting with computer"),
  WordHint("COOKIE", "Data stored by a web browser"),
  WordHint("CRASH", "Unexpected failure of a program"),
  WordHint("CREDENTIALS", "Authentication details"),
  WordHint("DEBUGGER", "Tool to find bugs in software"),
  WordHint("DEPLOYMENT", "Process of releasing software"),
  WordHint("DESKTOP", "Personal computer interface"),
  WordHint("DIALOGUE", "Interaction between user and software"),
  WordHint("DIRECTORY", "Folder to organize files"),
  WordHint("DISK", "Storage device"),
  WordHint("DLL", "Dynamic Link Library"),
  WordHint("DOCUMENTATION", "Information to understand or use software"),
  WordHint("DOMAIN", "Area of control or knowledge"),
  WordHint("EDITOR", "Software used to write code"),
  WordHint("EMULATOR", "Software that replicates hardware"),
  WordHint("ENCRYPTION", "Encoding data to secure it"),
  WordHint("EVENTHANDLER", "Responds to events like clicks"),
  WordHint("EXECUTE", "Run a program or instruction"),
  WordHint("EXPRESSION", "Combination of variables and operators"),
  WordHint("FRAMEBUFFER", "Memory holding image data"),
  WordHint("FREQUENCY", "How often something happens"),
  WordHint("FUNCTIONAL", "Programming paradigm from mathematical functions"),
  WordHint("GARBAGECOLLECTOR", "Automatically frees unused memory"),
  WordHint("GATEWAY", "Node connecting networks"),
  WordHint("GRAPH", "Data structure of nodes and edges"),
  WordHint("HARDWARE", "Physical parts of computer"),
  WordHint("HEARTBEAT", "Signal sent to check status"),
  WordHint("HOST", "Computer or device on a network"),
  WordHint("HTML5", "Latest version of HTML"),
  WordHint("HTTPREQUEST", "Client request to a server"),
  WordHint("IDEOGRAPHIC", "Symbol representing ideas or objects"),
  WordHint("INCORPORATE", "To include or blend in"),
  WordHint("INHERITANCE", "Properties passed from parent class to child"),
  WordHint("INPUT", "Data sent into a system"),
  WordHint("INSTANCE", "Specific realization of a class"),
  WordHint("INTEGRATION", "Combining parts into a whole system"),
  WordHint("INTERPRETER", "Software that runs code line-by-line"),
  WordHint("ITERABLE", "Object that can be looped over"),
  WordHint("KEYBINDING", "Shortcut to trigger commands"),
  WordHint("LAG", "Delay in response time"),
  WordHint("LICENSE", "Permission to use software"),
  WordHint("LINTING", "Analyzing code for errors"),
  WordHint("LOADBALANCER", "Distributes network traffic"),
  WordHint("LOCALHOST", "Local machine network address"),
  WordHint("LOGIC", "Rules for reasoning"),
  WordHint("LOOPBACK", "Network communication to self"),
  WordHint("MACADDRESS", "Unique identifier for network devices"),
  WordHint("MALWARE", "Malicious software"),
  WordHint("MANUAL", "User guide or instructions"),
  WordHint("MIDDLEWARE", "Software between data sources and applications"),
  WordHint("MOBILEAPP", "Software designed for mobile devices"),
  WordHint("MODULES", "Independent pieces of software"),
  WordHint("MONITOR", "Display screen"),
  WordHint("MUTABLE", "Object that can be changed"),
  WordHint("NATURAL", "Relating to real-world language"),
  WordHint("NETWORKING", "Connecting multiple computers"),
  WordHint("NODEJS", "JavaScript runtime environment"),
  WordHint("NULLABLE", "Value that can be null"),
  WordHint("OBJECTORIENTED", "Programming using objects"),
  WordHint("OPERATOR", "Symbol representing operations"),
  WordHint("OPTIMIZATION", "Making software run better"),
  WordHint("PACKET", "Unit of data transmitted"),
  WordHint("PARALLEL", "Running multiple operations simultaneously"),
  WordHint("PARAMETER", "Input for functions"),
  WordHint("PARSER", "Translates strings to code structure"),
  WordHint("PATCH", "Software update"),
  WordHint("PERFORMANCE", "How well software runs"),
  WordHint("PLATFORM", "Hardware or software foundation"),
  WordHint("PORT", "Communication endpoint"),
  WordHint("PROCESSOR", "Central unit executing instructions"),
  WordHint("PROTOCOL", "Rules for communication"),
  WordHint("QUERY", "Request for data"),
  WordHint("QUEUE", "Data structure for ordered elements"),
  WordHint("RECURSIVE", "Function calling itself"),
  WordHint("REFLECTION", "Inspecting program metadata at runtime"),
  WordHint("REGISTRY", "Database of configuration settings"),
  WordHint("REPOSITORY", "Storage of code"),
  WordHint("REQUEST", "Sent to a server for action"),
  WordHint("RESPONSE", "Server's reply to a request"),
  WordHint("ROUTER", "Directs network traffic"),
  WordHint("SCRIPT", "Set of commands"),
  WordHint("SERVER", "Serves data or resources"),
  WordHint("SESSION", "Duration of interaction"),
  WordHint("STACKOVERFLOW", "Error of too many function calls"),
  WordHint("SYNTAXERROR", "Mistake in code structure"),
  WordHint("TERMINAL", "Text interface for commands"),
  WordHint("THREADSAFE", "Code safe to use concurrently"),
  WordHint("TOKENIZE", "Split text into tokens"),
  WordHint("TOOLCHAIN", "Set of development tools"),
  WordHint("TRANSLATOR", "Converts code to machine-readable form"),
  WordHint("URI", "Uniform Resource Identifier"),
  WordHint("URL", "Web address"),
  WordHint("USERINTERFACE", "How user interacts with software"),
  WordHint("VARIABLESCOPE", "Visibility of variables"),
  WordHint("VIRTUALIZATION", "Creating virtual versions of resources"),
  WordHint("WEBASSEMBLY", "Binary instruction format for browsers"),
  WordHint("WEBSOCKET", "Full-duplex communication protocol"),
  WordHint("WORKFLOW", "Sequence of steps to complete tasks"),
  WordHint("XOR", "Exclusive OR logical operation"),
  WordHint("ZLIB", "Compression library"),
];

final Random _random = Random();

WordHint getRandomWord() {
  return hangmanWordList[_random.nextInt(hangmanWordList.length)];
}

bool isWordGuessed(String word, Set<String> guessedLetters) {
  for (var letter in word.split('')) {
    if (!guessedLetters.contains(letter.toUpperCase())) return false;
  }
  return true;
}
